language: python

python:
  - "3.3"
  - "3.4"
  - "3.6"


    
install:
  - pip install -r requirements.txt
  - pip install coveralls


script:
  - pytest --cov=app/v1 tests/

after_success:
  - coveralls
  
